### ISSUE TITLE
[Bug] tachidesk jui windows not installing extension's 

### ISSUE THREAD

**Issue by Xellerate005** [Suwayomi/Tachidesk-JUI#43]
## Device information
- Tachidesk-JUI version: version 1.2.1
- Operating System: windows 10 20h2
- Desktop Environment: windows
- Server Type: extension
- Client JVM version: msi version
- Server JVM version: msi
## Steps to reproduce
1. Download extension
2. Enjoy

### Expected behavior
Extension should install and then be usable
### Actual behavior
Doesnt install, when clicked refreshed the page whenever the install button is clicked.

**Comment by Syer10** [comment]
Sounds like your running into https://github.com/Suwayomi/Tachidesk-Server/issues/237.
Its not a JUI issue as its a server issue, but it is caused by a bad Java version, usually found in Oracle Java, try uninstalling your Oracle Java and install [Temurin 8](https://adoptium.net/?variant=openjdk8&jvmVariant=hotspot)
