### ISSUE TITLE
[Bug] Tachidesk fails to connect to the server

### ISSUE THREAD

**Issue by andreacorinti** [Suwayomi/Tachidesk-JUI#68]
## Device information
- Tachidesk-JUI version: v1.3.0
- Operating System: Arch Linux
- Desktop Environment: KDE plasma 5.26.2
- Server Type: Internal
- Client JVM version: java-19-openjdk
- Server JVM version: java-19-openjdk

## Steps to reproduce
1. Launch Tachidesk-JUI
2. Trying to connect to the server

### Expected behavior
Tachidesk connecting to the server

### Actual behavior
Connection to the server fails. 

[here is the terminal log](https://pastebin.com/zS5k208S)

I've recently changed OS, in my previous system Tachidesk-jui worked perfectly which is strange - maybe something openjdk related? (I was using 17 before)

installed with `yay -S tachidesk-jui`

**Comment by Syer10** [comment]
It looks like Javalin is trying to use a Loom threadpool since Loom is available when using the preview flag in Java 19, but JUI doesn't enable the preview flag so its a false positive. I would suggest downgrading to Java 17 for now, it might be fixed later on but its mostly a server-side/Javalin issue
